services:
  # Stalwart Mail Server
  stalwart:
    hostname: mail-vps
    image: stalwartlabs/stalwart:latest
    container_name: stalwart
    restart: unless-stopped
    ports:
      - "25:25"    # SMTP
      - "465:465"  # SMTPS
      - "587:587"  # Submission
      - "143:143"  # IMAP
      - "993:993"  # IMAPS
      - "110:110"  # POP3
      - "995:995"  # POP3S
      - "4190:4190" # ManageSieve
      - "9000:8080" # Admin UI (змінили порт з 8080 на 9000)
    volumes:
      - ./stalwart_data:/opt/stalwart
    networks:
      - mailer_network

  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    volumes:
      - rainloop:/rainloop/data
    depends_on:
      - stalwart
    networks:
      - mailer_network
    ports:
      - "9001:8888"

volumes:
  rainloop:

networks:
  mailer_network:
    external: true